### ISSUE TITLE
Scuffed Ideas / Design Thread

### ISSUE THREAD

**Issue by AnatoleAM** [SevenTV/SevenTV#1]
Some initial ideas

- Many emote slots 
- Support different emote types like wide, animated (gif/apng), combinations, etc
- Sync instantly when MODS change channel emote, no last spams FUNDETECTED

**Comment by 3Gigs** [comment]
VeryPog

**Comment by 3Gigs** [comment]
The main goal of the project should prioritize easy to use moderation tools for managing emotes OMGScoots
