### ISSUE TITLE
Emotes in Pinned Messages

### ISSUE THREAD

**Issue by LincolnKne** [SevenTV/SevenTV#102]
### Tell us about your Wish

Currently when a message that has 7tv emotes in it is pinned in a twitch channel the emotes do not show in the pinned message, this is a small feature I would like to see!

### Participation

- [ ] I am willing to submit a pull request to implement this

**Comment by lennartkloock** [comment]
This is a issue related to the [extension](https://github.com/SevenTV/Extension), please create an issue there.
