### ISSUE TITLE
Broken Image in Shared Chat

### ISSUE THREAD

**Issue by shuffgy** [SevenTV/SevenTV#107]
### What seems to be the problem?

Its only with one streamer friend of mine  and i cant find out why this should happen. But i want to report it:

![image](https://github.com/user-attachments/assets/dde62fbc-37a7-4ecb-8be7-1d1f30af178f)

The srcset string is 

`https://static-cdn.jtvnw.net/jtv_user_pictures/8e9d5778-ded9-4726-9df0-f17c27488756-profile_image-228x28.png 1.6x, https://static-cdn.jtvnw.net/jtv_user_pictures/8e9d5778-ded9-4726-9df0-f17c27488756-profile_image-270x70.png 3.8x` 

Its working when disabling 7tv browser extension

### Operating System

Microsoft Windows

### Browser

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, etc.)

### How do we replicate that?

Wait for him to stream with someone? Mostly sundays :D

**Comment by lennartkloock** [comment]
This is a issue related to the [extension](https://github.com/SevenTV/Extension), please create an issue there.
