### ISSUE TITLE
[Bug] Low quality emotes

### ISSUE THREAD

**Issue by dpi** [SevenTV/SevenTV#111]
**Describe the bug**

Emotes are particularly low quality, assumedly because I'm running a standard 4K screen. Pixels look doubled.

Probably a regression since #34

**To Reproduce**

- 4K 3840x2160
- Win10, 150% scaling (default)
- Fx 91.0
- Addon version 1.6.0

**Expected behavior**

Emotes should use hi-res versions, or at least shouldnt look like they have been pixel-doubled; fall back to browser upscaling. 

**Screenshots**

7TV enabled, BTTV disabled, bad, low res:

![image](https://user-images.githubusercontent.com/21850/129384065-50a6bb19-828b-41a4-8cb2-2a951c4c98e2.png)

7TV disabled, BTTV enabled, good, hi-res:

![image](https://user-images.githubusercontent.com/21850/129384037-f2960bb0-ac26-4efa-98b0-9d894a6c249f.png)

**Comment by AnatoleAM** [comment]
I'm not sure what causes this and I'm usually unable to replicate this as I don't own a 4K screen. It's most likely some weird auto-scaling Windows does.

**Comment by dpi** [comment]
Perhaps this may be clue enough:

Left: 7TV + BTTV enabled (low res)
Right: Only BTTV (high-res)

![image](https://user-images.githubusercontent.com/21850/129392037-dd43e756-8d63-44a2-9900-b3002064a398.png)

**Comment by AnatoleAM** [comment]
That's a pretty big difference indeed. Not nearly as noticeable on 1080p or even 1440p. Seems like it's done via [srcset](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images). I'll take another look at this for the upcoming 1.6.1

**Comment by dpi** [comment]
You got it. Thanks for taking a look, it's truely an eyesore.

**Comment by AnatoleAM** [comment]
@dpi could you try this build and let me know if it made any kind of change? I can't see a difference myself, but *in theory* it should better on your screen. (see install instructions in the README)
[pr-113.zip](https://github.com/SevenTV/SevenTV/files/6985178/pr-113.zip)

**Comment by AnatoleAM** [comment]
After some testing and adjusting responsive sizing I got this to work. Here's the difference:

### Current
![image](https://user-images.githubusercontent.com/9599344/129444071-b5bc9407-280e-4871-80d4-f9dabb6060c3.png)

### Pull Request #113
![image](https://user-images.githubusercontent.com/9599344/129444079-d48e5832-6073-473f-bf0b-0e0e8b1c13bb.png)

**Comment by dpi** [comment]
Tested the extension in the zip, looks much better.

Though the issue remains that pixels look quite odd. Even when an emote isnt animated, the 7TV emote is **jittering** (!!!) ever so slightly when chat is not moving. I traced this down to a this being set by the 7TV stylesheet: `image-rendering: crisp-edges;`, reading the spec, it doesnt look like the best application of this property is emotes. Can it be removed?

Left: with crisp-edges, Right: without.

![image](https://user-images.githubusercontent.com/21850/129447684-29f5dd0e-8189-48bf-a653-8b9aad506a30.png)

**Comment by AnatoleAM** [comment]
@dpi There were some additional changes to scaling as well, try this and let me know:
[pr-115.zip](https://github.com/SevenTV/SevenTV/files/6986535/pr-115.zip)

**Comment by dpi** [comment]
Yep, that does the trick. Thanks!

![image](https://user-images.githubusercontent.com/21850/129448288-0af31b25-41b2-40d3-9d9e-e99a002a2633.png)

**Comment by AnatoleAM** [comment]
Fixed by #113 and #115 and deployed as part of [Version 1.6.1](https://github.com/SevenTV/SevenTV/releases/tag/1.6.1)
