### ISSUE TITLE
Extension randomly stops working completely

### ISSUE THREAD

**Issue by Cariyla** [SevenTV/SevenTV#127]
Since a couple days 7tv randomly stops working completely, this seems to happen mostly when I open a new browser window, opening a new tab in the same window doesn't cause this to happen but dragging the tab out to a new window does. All 3rd party emotes stop displaying and the emote picker shows no available 3rd party emotes for the channel. Closing all browser windows completely sometimes fixes this but often also doesn't.

Win10 Enterprise LTSC, Firefox 92.0 64-bit, 7tv 1.6.2

**Comment by AnatoleAM** [comment]
This may be tied to the reliance on other third party services to be available, I'll be pushing an update soon removing this dependency.
