### ISSUE TITLE
Doesn't seem to work with Alternate Twitch Player

### ISSUE THREAD

**Issue by slow-down** [SevenTV/SevenTV#131]
Like the title says. This plugin doesn't work with the Alternate Twitch Player. The other 2 big emote plugins work completly fine for years with that plugin... Is there some kind of a setting for me to enable the support or not? Because theres no way im uninstalling alternate twitch player because my internet sucks to much for the normal player. Any tips on how to get it working or is it literaly not possible? Also I don't know if this support is provides by the player itself or by the other plugins, if thats the players fault than im sorry for posting here.

**Comment by AnatoleAM** [comment]
See #71
