### ISSUE TITLE
Concurrent Emote Set Modifications

### ISSUE THREAD

**Issue by RyanPotat** [SevenTV/SevenTV#134]
### What seems to be the problem?

Currently when sending concurrent requests to update the same emote set, we receive `transaction failed` errors.

In the previous implementation, the requests would all be received without issue, but it would sequentially process the emote set modifications in the backend (ensuring emote set is not larger than max size). 

I know batch updates are planned for emote sets, but maybe this could be re-implemented in the meantime.

### Browser (if relevant)

None

### How do we replicate that?

1. Send multiple requests to update a single emote set concurrently
2. ~90% will fail due to transaction errors

### Relevant log output

```shell
N/A
```

**Comment by lennartkloock** [comment]
@RyanPotat Is this still a problem?

**Comment by RyanPotat** [comment]
It is not an issue anymore, thank you
