### ISSUE TITLE
Removing emotes doesn't emit right events

### ISSUE THREAD

**Issue by blxryer** [SevenTV/SevenTV#137]
### What seems to be the problem?

Hi, i have the problem that i added an emote with an bot on twitch, but 2 people tryed to add the emote at the same time with the bot, it was the same emote with 2 different names, it added it two times in the set, this happens when you do the api request to add the emote two times at the same time so the first one is not finished, so the seconds request doesnt has the emote in the database and also thinks like the first request that also thinks that the emote is not in the set, and adds it to the database/set. After that i also cant remove the emote, when i remove one of them it removes it but the seconds one it says   "Error BAD_REQUEST
emote not found in set" on the website, but the box is green in this set. But its not consistent like this, sometimes i get this error but other times like now with the emote https://7tv.app/emotes/01G0Z7JXC80005B2DBC6FW4MKY i removed the emote an it removed the emote with both names but in chatterino its enabled, but on the website https://7tv.app/emote-sets/01H2DW64V8000EYM9JSHXBB84W its not in set it removed one name of it in chatterino but not both.

### Browser (if relevant)

None

### How do we replicate that?

You just need to request to add the same emote with gql 2 times with different names at the same time

**Comment by lennartkloock** [comment]
This is a feature, not a bug. Our new implementation allows emotes to be added multiple times to the same set under different names. The problem is that the website doesn't respect that because it was different before. When you try to remove the emote from the set, all identical emotes (with the same id) are removed too.

This is not related to sending the requests at the same time.

Does that answer your question?

**Comment by RyanPotat** [comment]
It seems EventAPI does not dispatch events for all emotes removed from the set when they share the same emote ID. It only emits a single removal, but they are all removed from the set.

The extension removes all variants, but chatterino (and probably any other client) does not, so it is left in cache.

**Comment by lennartkloock** [comment]
True, we will have to fix that
