### ISSUE TITLE
Special Personal Emote Sets Aren't Listed in User emote_sets

### ISSUE THREAD

**Issue by Johnnycyan** [SevenTV/SevenTV#140]
### What seems to be the problem?

When querying https://7tv.io/v3/gql for a user's emote_sets the special personal emote sets like NNYS and Sub Event 2023 aren't listed. I currently can't find any way to query for these. Also the entitled bool is ignored.

### Browser (if relevant)

None

### How do we replicate that?

Query https://7tv.io/v3/gql with:
```
userByConnection(id: "100769416", platform: TWITCH) {
  emote_sets(entitled: true) {
    id
    name
    flags
  }
}
```

I own the 2 special emote sets listed above but they do not appear here anymore like they used to, only the standard personal emote set is there.

**Comment by TroyKomodo** [comment]
fixed.
