### ISSUE TITLE
7TV Settings are completely unreadable in light mode

### ISSUE THREAD

**Issue by NS2555** [SevenTV/SevenTV#141]
**Describe the bug**
7TV Settings have an issue, that if you use lightmode, most of the most important text is white, which combining with a white background, causes the text to be completely invisible.

**To Reproduce**
1. Go to 'twitch.tv'
2. Click on the '7TV Settings'
3. (Get sunglasses and) Turn on the light mode
4. You should be able to see the problem

**Expected behavior**
Settings open, and you can read every single piece of text there is in the settings, because it's of a dark color, instead of white

**Screenshots**
How it looks in chromium:
![chrome_p2atUehApZ](https://user-images.githubusercontent.com/18615981/134213890-0143abc1-1994-4b38-8717-12f3131a0699.png)
How it looks in firefox:
![firefox_rxhY6rxOyF](https://user-images.githubusercontent.com/18615981/134214499-6bf4606a-99f4-4ad4-8d22-2e50fad5f35f.png)

**Version:**
Version 1.6.2 in Chromium
Version 1.6.2 in Firefox

**Comment by Excellify** [comment]
Included a fix in #140
