### ISSUE TITLE
Emote list on website doesn't work if window is too wide

### ISSUE THREAD

**Issue by 73om** [SevenTV/SevenTV#146]
### What seems to be the problem?

If my browser window is too wide (seemingly at the point where a 21st column of emotes should be displayed), 7tv.app/emotes will not show me any emotes and just says "No emotes found" in the centre.
This behaviour has been consistent for the last few weeks on macOS under Chrome, Firefox and Safari, all updated. The width that triggers this issue is a bit narrower than my 4k screen, so a maximized window means I cannot see any emotes until I resize it small enough to have 20 or fewer emote columns, <3692 px viewport width roughly. 

I have included 2 screenshots of two widths just slightly either side of the point that triggers this:
![Screenshot 2024-11-19 at 20 05 33](https://github.com/user-attachments/assets/d7213deb-a4a0-40ff-a9e6-89c3a49190c2)
![Screenshot 2024-11-19 at 20 05 14](https://github.com/user-attachments/assets/38a213a6-9f88-41f6-b358-16b0a59146de)

### Browser (if relevant)

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, etc.)

### How do we replicate that?

1: Visit 7tv.app/emotes
2: Resize window to where 21 emote columns would be used, this then shows "No emotes found" instead of the grid of emotes.
3: Resize window back to where 20 or fewer emote columns would be used, emotes are accessible again.

**Comment by 73om** [comment]
I also have only just noticed that the issue also only happens if the height of the window is large enough as well. if the window is only 1080 px tall or so but > 3692 px wide it'll do the 21 columns fine, but go too much bigger in height then you need the width to be under 3692 to display anything.

**Comment by lennartkloock** [comment]
Not related to this repo

**Comment by 73om** [comment]
Thanks @lennartkloock for your response however I don't understand how it's not related to this repo. 

The bug looks to be within the code here which I have had a look at briefly after seeing your response.

I believe the issue to be in apps/api/src/http/v3/gql/queries/emote.rs - in which the emotes function and the construction of EmoteSearchResult look like they limit the maximum search results from the emotes page to 100. When the 7tv.app/emotes page is widened too far on display - a grid configuration of **over 20** columns by **5 rows** the search function attempts to retrieve over 100 results - it seems this search is limited by code in this repo to 100 results and it craps out and displays "No Emotes Found" instead of the grid of emote results when asked to show more than that.  This would also explain why it works when you shrink the window enough vertically while it is over 20 columns wide, once it gets down to 4 rows, it's still requesting under 100 results per page at that point.

The beta version of the site doesn't appear to be affected by this, I assume it's using a different method for its page as it progressively adds more results to the page in smaller chunks or just operates differently, idk.

**Comment by lennartkloock** [comment]
Hi @73om , sorry for not explaining my reasoning before. I was assuming this bug is entirely related to the website which is not in this repo. (https://github.com/SevenTV/Website) It is true that the per page limit is 100 but that is intended. In the case that the website would exceed this limit it should still load 100 emotes. This means this issues it not related to the API but rather the website.
