### ISSUE TITLE
[Bug] Youtube: Addon breaks name highlighting when tagged with @

### ISSUE THREAD

**Issue by robmonte** [SevenTV/SevenTV#149]
**Describe the bug**
Normally in a youtube stream chat, when someone @ 's you with your username, your name is highlighted. With 7TV installed, the names no longer highlight.

**To Reproduce**
1. Go to a youtube stream chat
2. Have someone else tag your username with @ 
3. Observe plain formatting

**Expected behavior**
It should be brightly colored and bolded

**Version:**
2.0.0

**Comment by AnatoleAM** [comment]
Thanks for letting me know, will take a look for the next version

**Comment by robmonte** [comment]
Fixed in the above merge
