### ISSUE TITLE
[Bug] Some bttv emotes are broken and don't show

### ISSUE THREAD

**Issue by Rmin-Sadigh** [SevenTV/SevenTV#151]
**Describe the bug**
7tv fails to load some emotes while bttv extension can
Broken emotes are shown like this
![image](https://user-images.githubusercontent.com/61507499/134814020-24bf9eab-1980-4b16-8d0e-0fc7f288c253.png)
Right-clicking the emote and opening in new tab shows a "404 Not Found" message

**To Reproduce**
1. Open any twitch channel with an active chat
2. Wait to see attached image as any emote

**Expected behavior**
All emotes should show normally

**Version:**
2.0.0

**Note**
This might be unrelated; some bttv emotes load properly (the ones that show up in the emote menu). These emotes have way longer links than the faulty ones. example:
https://cdn.betterttv.net/emote/386780/2x (Faulty emote)
vs
https://cdn.betterttv.net/emote/609431bc39b5010444d0cbdc/1x (Working emote)

**Comment by Rmin-Sadigh** [comment]
**Update**: it seems the emotes are FFZ emotes and the extension mistakenly identifies them as bttv emotes and loads them with the wrong URL
the working emote URL for the above example is 
https://cdn.betterttv.net/frankerfacez_emote/386780/1
instead of 
https://cdn.betterttv.net/emote/386780/1x

**Comment by Excellify** [comment]
This seems to be caused by the margin-right that is added to all message elements
