### ISSUE TITLE
Ability to toggle extension "off" on twitch.tv on firefox

### ISSUE THREAD

**Issue by KeppanaD3sti** [SevenTV/SevenTV#152]
### Tell us about your Wish

Like on chrome browser you can click the extension to enable it, there isnt such option on firefox yet, so id like to have option to turn extension off at **twitch.tv** on **firefox** just cause i dont want to use multiple extensions doing the same things on twitch.tv 
but i do like to use this extension on different websites like kick and youtube

### Additional Info

![{2F717417-7803-4A3E-B9AB-7F7B77E47001}](https://github.com/user-attachments/assets/2b6c0944-a715-4fe6-aff6-174846f4de1e)

### Participation

- [ ] I am willing to submit a pull request to implement this

**Comment by lennartkloock** [comment]
This issue is related to the extension
