### ISSUE TITLE
Platform deleted emotes still get counted on `emoteSet` mutations

### ISSUE THREAD

**Issue by brian6932** [SevenTV/SevenTV#155]
### What seems to be the problem?

Add an emote to a set with 1 slot less than the `.emoteSet.capacity` value (if this was done multiple times, you have to subtract the attempt count from the capacity). You have lost an emote slot, and it's no longer visible within the set. In the go version of the API, the platform deleted emotes would be visible within the set, so you could query the set, and then remove the respective `.emoteSet.emotes.id` manually. However, now in the rust rewrite, they're not even visible within the set, nor counted in the `.emoteSet.emote_count`. This makes removing platform deleted emotes extremely difficult.

### Browser (if relevant)

None

### How do we replicate that?

1. Upload an emote (`01JE98CTTTES18ACRR3K4Q3E09`).
1. Create an emote set.
   ```gql
   mutation{createEmoteSet(user_id:"01F6RA600R000ATZXMPM5X7AC2"data:{name:"foo"}){id}}
   ```
   ```json
   {"data":{"createEmoteSet":{"id":"01JE97Y38EEXAEGY3H19PBV75D"}}}
   ```
1. Set it's capacity to 1.
   ```gql
   mutation{emoteSet(id:"01JE97Y38EEXAEGY3H19PBV75D"){update(data:{capacity:1}){capacity}}}
   ```
   ```json
   {"data":{"emoteSet":{"update":{"capacity":1}}}}
   ```
1. Add the emote to the set.
   ```gql
    mutation{emoteSet(id:"01JE97Y38EEXAEGY3H19PBV75D"){emotes(id:"01JE98CTTTES18ACRR3K4Q3E09"action:ADD){id}}
   ```
   ```json
   {"data":{"emoteSet":{"emotes":[{"id":"01JE98CTTTES18ACRR3K4Q3E09"}]}}}
   ```
1. Delete the emote from the platform.
   ```gql
   mutation{emote(id:"01JE98CTTTES18ACRR3K4Q3E09"){update(params:{deleted:true}){id}}}
   ```
   ```json
   {"data":{"emote":{"update":{"id":"01JE98CTTTES18ACRR3K4Q3E09"}}}}
   ```
1. Query the now supposedly _empty_ set.
   ```gql
   {emoteSet(id:"01JE97Y38EEXAEGY3H19PBV75D"){emotes{id}emote_count capacity}}
   ```
   ```json
   {"data":{"emoteSet":{"emotes":[],"emote_count":0,"capacity":1}}}
   ```
1. Add a random emote.
   ```gql
   mutation{emoteSet(id:"01JE97Y38EEXAEGY3H19PBV75D"){emotes(id:"01F6MZGCNG000255K4X1K7NTHR"action:ADD){id}}}
   ```
   ```json
   {"data":{"emoteSet":null},"errors":[{"message":"BAD_REQUEST emote set is at capacity","locations":[{"line":1,"column":52}],"path":["emoteSet","emotes"],"extensions":{"code":"BAD_REQUEST","fields":{},"message":"BAD_REQUEST emote set is at capacity","status":400}}]}
   ```
 1. Attempt to remove the deleted emote, which no longer exists on the platform, within the API's _empty_ set.
    ```gql
    mutation{emoteSet(id:"01JE97Y38EEXAEGY3H19PBV75D"){emotes(id:"01JE98CTTTES18ACRR3K4Q3E09"action:REMOVE){id}}}
    ```
    ```json
    {"data":{"emoteSet":{"emotes":[]}}}
    ```
1. Attempt to add a random emote again, and see that it works now.
   ```gql
   mutation{emoteSet(id:"01JE97Y38EEXAEGY3H19PBV75D"){emotes(id:"01F6MZGCNG000255K4X1K7NTHR"action:ADD){id}}}
   ```
   ```json
   {"data":{"emoteSet":{"emotes":[{"id":"01F6MZGCNG000255K4X1K7NTHR"}]}}}
   ```

**Comment by lennartkloock** [comment]
@brian6932 Please confirm this is fixed
