### ISSUE TITLE
Frankerfacez badge

### ISSUE THREAD

**Issue by Chassss** [SevenTV/SevenTV#158]
### What seems to be the problem?

While using 7tv the frankerfacez supporter badge is completely removed from chat, started happening around 1-2 months ago and if i were to disable 7tv (which has ffz support) and just the ffz extension then im able to see ffz supporter badges again

Also just a side note it'd be nice to be able to disable betterttv and ffz support for this extension since its only caused bugs for the past 3 years or at least tell the user in some way shape or form that 7tv isnt only 7tv and its all 3 extensions (emote support wise)

![Untitled5](https://github.com/user-attachments/assets/ac7607aa-f9ec-4dc2-aaa0-0f7933ea38ab)

### Browser (if relevant)

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, etc.)

### How do we replicate that?

have 7tv stable v3.0.9 active or have 7tv nightly v3.0.10.1000 active

**Comment by lennartkloock** [comment]
This issue is related to the extension

**Comment by Chassss** [comment]
yup thats pretty dope, closes a bug as "not planned" because of this line:
https://github.com/SevenTV/SevenTV/blob/24420ea062ab93e26542fc8b90fcc704d488373a/apps/api/src/http/v3/rest/config.rs#L40

overriding another extensions functionality without ever telling the user, 7tv has slowly turned into bttv. 7tv currently has forced built in betterttv support and forced built in ffz support, my screenshot i sent the left picture is using ONLY 7tv with no other extensions installed since it has ffz and bttv built in like i just said, and the right side is me disabling 7tv completely and showing how ffz is suppose to work but i get the response "This is related to the extension". also since 7tv has built in bttv and ffz support it completely overrides the other 2 extensions making some badges invisible and making a ton of settings un-useable unless i wanna make my own version of 7tv with bttv and ffz stripped out of it
