### ISSUE TITLE
[Bug] overblown emotes

### ISSUE THREAD

**Issue by bitesh** [SevenTV/SevenTV#166]
**Describe the bug**
I get these overblown huge-ass emotes (usually big-ass stars, but today I saw an alien) whenever I join a new chat

**To Reproduce**
1. Change channels
2. Post an emote (I don't know which specific emotes cause this, but I often get the huge star before another emote)
3. Look at chat

**Expected behavior**
I don't even know if it's a bug, but expected it to not insert any emotes besides the ones I actually type, and they be the correct size. (the huge star, with alien, ppl seem to have actually typed "alien")

**Screenshots**
![Screenshot from 2021-10-14 14-46-11](https://user-images.githubusercontent.com/88059149/137330210-6e9afb6c-1879-47bb-9943-5a77b4be07c6.png)
![Screenshot from 2021-10-16 02-00-56](https://user-images.githubusercontent.com/88059149/137567621-ae2cb292-23a4-4c20-a877-846bbca6c5f6.png)

**Version:**
2.0.0

**Comment by AnatoleAM** [comment]
This is a known conflict with the BetterTTV extension.
