### ISSUE TITLE
Remove emote dialog always shows "Cat Emotes" as the emote set name

### ISSUE THREAD

**Issue by BennyExtreme** [SevenTV/SevenTV#170]
### What seems to be the problem?

When trying to delete an emote from an emote set the dialog always shows "Cats Emotes" as the emote set name
![img](https://github.com/user-attachments/assets/51e93ca0-138d-4b91-a5e5-f0c0a3c751d5)

Here
https://github.com/SevenTV/SevenTV/blob/a0e4fa9d36018fb20e12dc8d45711c86a920fe6a/apps/website/src/components/dialogs/remove-emotes-dialog.svelte#L11

### Browser (if relevant)

None

### How do we replicate that?

1. Open an emote set page
2. Enable the Selection Mode
3. Select one or more emotes
4. Click the delete button
5. The dialog title is "Remove selected emotes from Cat Emotes"
The title should instead show the actual name of the emote set instead of "Cat Emotes"

**Comment by WeaselOnaStick** [comment]
How are you supposed to remove emotes from the set then? This is one of the most important parts and now it's... not planned?

**Comment by BennyExtreme** [comment]
@WeaselOnaStick For now you can still use the `Add to` button on a single emote page to remove/add it to one or multiple emote sets, the same way for the [old site](https://old.7tv.app/), but the button is `Use Emote` instead.
Also, @lennartkloock just said it's not there yet, so its now hidden, but it actually means that they will take their time to implement that, but after it will be there in the future.
