### ISSUE TITLE
Option “Allow sending the same message twice“ does not work for me

### ISSUE THREAD

**Issue by deolic** [SevenTV/SevenTV#182]
I'm using Mozilla Firefox.

![obraz](https://user-images.githubusercontent.com/45566599/141328073-3e4c1dd8-b143-456f-b24a-4eef5ddb296d.png)

**Comment by AnatoleAM** [comment]
This is a known conflict with the BetterTTV browser extension.

**Comment by nYCSTs** [comment]
I am having the same problem, even without BetterTTV or FrankerZ extension.
