### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by shanglin10** [SevenTV/SevenTV#186]
**Twitch chat cant display text properly.**

when i go to ADDONS manager then disable the 7TV, everything going well.

BTW,my desktop uses same account and web browser,but the bug doesnt exise.

![1637727210730](https://user-images.githubusercontent.com/57247941/143174956-ad18ac9b-282b-48f2-b441-ec2a78205e1f.jpg)

**Version:**
7TV:2.0.2
firefox:72.0.1.
OS:Win 10 home

**Comment by AnatoleAM** [comment]
While we were not able to reproduce this issue, I will assume this is no longer happening given it has been a few months. If it is still the case feel free to re-open.
