### ISSUE TITLE
The browser plugin not working in the embed twitch chat iframe [Bug] 

### ISSUE THREAD

**Issue by nepeee** [SevenTV/SevenTV#187]
**Describe the bug**
The browser plugin not working in the embed twitch chat iframe.

**To Reproduce**
<iframe src="https://www.twitch.tv/embed/[channel]/chat?darkpopout&parent=[parentdomain]"></iframe>
where [channel] is the name of the channel [parentdomain] is the domain/path of the site where the embed is placed.
Both bttv and ffz works.

**Expected behavior**
The plugin is working in the twitch embed chat :)

**Version:**
All current, checked in chrome and firefix.

**Comment by dillon-cullinan** [comment]
Common use case where this bug comes into play is the use of alternative players for Twitch which are commonly used to get around Twitch ads.

**Comment by AnatoleAM** [comment]
This was implemented by #193 and released with version [2.1.2](https://github.com/SevenTV/SevenTV/releases/tag/2.1.2).

**Comment by HukilauKohi** [comment]
I am using version 2.2.2 for Chrome and am not able to see/use the 7TV plugin when viewing an embed chat.

In the image below the left side is chat when viewed from the streamers channel, while the right is viewed from: 
`https://www.twitch.tv/embed/[channel]/chat?darkpopout&parent=twitch.tv`


![Chat Embed](https://user-images.githubusercontent.com/105951275/173679126-17b1a7ce-6b1d-4441-a047-e10dc0a80a0a.png)

Should this be flagged as a new issue/bug, or am I missing something here?

**Comment by tlstommy** [comment]
was this ever solved? Im getting the same issue embedding into an iframe

**Comment by nepeee** [comment]
> was this ever solved? Im getting the same issue embedding into an iframe

It was but then broke again :(
