### ISSUE TITLE
Username mentions are repeated in bold text

### ISSUE THREAD

**Issue by Rmin-Sadigh** [SevenTV/SevenTV#19]
Any username mention creates another duplicate near the first one, written in bold font. the issue is mitigated when I disable the extension and refresh. Sometimes the first channel doesn't show this problem and it only appears when I join another stream. I tried disabling bttv but it didn't fix the problem.

**Comment by AnatoleAM** [comment]
Fixed in 1.5.2 ca9d082de2cf35ce05965815feabe3b9d32f6986
