### ISSUE TITLE
[Bug] Christmas Paints won't show in firefox extension

### ISSUE THREAD

**Issue by EpicXd** [SevenTV/SevenTV#192]
**Describe the bug**
The Christmas Paints won't show in the 7tv Firefox Extension 
**To Reproduce**
1. Open Firefox 
2. Install the 7tv plugin 
3. Type in a chat with the paint name effect
4. No changes just regular twitch color 

**Expected behavior**
Gradient colors in native chat if the extension is installed

**Screenshots**
![Bugged](https://user-images.githubusercontent.com/29181249/147357678-27b3ec51-1438-4ef7-a939-95e691223edd.PNG)
Left is Firefox and Right is Google Chrome 

**Version:**
Latest Version (2.1.0) as off 12/24/2021 8:00 AM CST

**Comment by AnatoleAM** [comment]
This has been addressed by #191 and will be resolved once a new version is published on the Firefox store
