### ISSUE TITLE
Chat overlap double

### ISSUE THREAD

**Issue by Neppsz** [SevenTV/SevenTV#193]
### What seems to be the problem?

Occasionally the chat just doubles and overlaps over itself, and the bandaid solution for it is to hide and re-show the chat.

### Browser (if relevant)

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, etc.)

### How do we replicate that?

Literally just wait and it happens eventually. I have tried also disabling 7TV for a few days to confirm and it only happens with this extension enabled.
![a](https://github.com/user-attachments/assets/7ce7131e-81a1-4af8-a63d-eedf9592a119)

**Comment by lennartkloock** [comment]
This issue is related to the extension, please open an issue there
