### ISSUE TITLE
Tab Autocomplete not autocompleting 7tv emotes

### ISSUE THREAD

**Issue by shawjus** [SevenTV/SevenTV#20]
If a BTTV emote or chat user begins with the autocomplete token, they will be prioritized and the 7tv emote will be ignored by further tab presses.
Ex. Typing "feels" and pressing tab will cycle through FeelsBadMan etc. but will never find FeelsWeirdMan unless you type "feelsw".
Also, autocomplete should leave a space after completing an emote, like BTTV does.

**Comment by AnatoleAM** [comment]
7TV's autocompletion is rather primitive currently, it's receiving improvements in the next patch

**Comment by AnatoleAM** [comment]
Auto-complete is a complete feature in 1.5.5.
