### ISSUE TITLE
[Bug] 7tv not loading unless refreshed. 

### ISSUE THREAD

**Issue by BitESKrunker** [SevenTV/SevenTV#203]
7tv on Chrome, Version 97.0.4692.71 (Official Build) (64-bit) for Windows doesn't load on first load on Twitch unless you reload. (English waw) 

Steps:
1. Load into any stream
2. 7tv doesn't load
3. Refresh
4. 7tv works again Pog

Proof:
[Video Link/ Streamable] https://streamable.com/ffou5n

**Comment by AnatoleAM** [comment]
This was fixed by #202 and is currently pushed, but has not yet been approved on Chrome.

**Comment by BitESKrunker** [comment]
Oh okay tyty
