### ISSUE TITLE
Auto-complete not working on Twitch emotes [Bug] 

### ISSUE THREAD

**Issue by Master-64** [SevenTV/SevenTV#204]
**Describe the bug**
When trying to type any Twitch emote, a triangle and square icon appears above it (7TV trying to show the emote in a bigger picture), before deleting the emote text.

**To Reproduce**
1. Type something like "LUL" in the chat window (or try to auto-complete any Twitch emote)
2. Press Enter
3. The text will disappear

**Expected behavior**
The text doesn't disappear

**Screenshots**
Screenshot of problem: [Discord Image](https://cdn.discordapp.com/attachments/803744047805366323/933670263923560508/2740.png)

**Version:**
2.1.3

**Comment by AnatoleAM** [comment]
This is a Twitch experiment currently affecting 5% of users, not a 7TV feature. Currently you can follow these steps to manually disable that experiment, which will return normal functionality.

![image](https://user-images.githubusercontent.com/9599344/150323972-c813ea07-9f5f-4751-869f-0707fdf7643f.png)
