### ISSUE TITLE
7TV emote menu not working as intended [Bug] 

### ISSUE THREAD

**Issue by Master-64** [SevenTV/SevenTV#205]
**Describe the bug**
Clicking on an emote through the emote menu does not work.

**To Reproduce**
1. Open up the 7TV emote menu
2. Click any emote
3. See error

**Expected behavior**
Emote text should appear in your current chat message.

**Version:**
2.1.3

**Comment by AnatoleAM** [comment]
See https://github.com/SevenTV/SevenTV/issues/204#issuecomment-1017352961.
