### ISSUE TITLE
The browser emote list needs some improvements

### ISSUE THREAD

**Issue by NS2555** [SevenTV/SevenTV#21]
There are several issues that I have noticed with the 7TV browser extension,

The main issue, is that this extension doesn't have a light theme version of it, and the only thing that changes, is the font color, which creates several accessibility, and general purpose issues for light theme users.

The current emote list button blends in with the background easily:
![image](https://user-images.githubusercontent.com/18615981/120022101-9523aa00-bff4-11eb-9b19-082a9ba072fb.png)
 

While it should be more like this:
![Fixed_Thing](https://user-images.githubusercontent.com/18615981/120023050-ef713a80-bff5-11eb-95b8-d441f72a5eda.png)

Another issue is with the way that the emote menu works by itself, if you open it in light theme, the font is black, on a gray background,  which causes issues with contrast, this issue is seen throughout all parts of this extension.

![image](https://user-images.githubusercontent.com/18615981/120023929-209e3a80-bff7-11eb-88ed-d57d00ccaf82.png)

A solution to this problem would be changing the background colors to fit more with a light theme as shown in this example below:

![Fixed_Light_Theme](https://user-images.githubusercontent.com/18615981/120025046-c30aed80-bff8-11eb-9f2d-a7206efaff73.png)

**Comment by AnatoleAM** [comment]
Thanks for the detailed report, this is being addressed very shortly in the upcoming patch

**Comment by AnatoleAM** [comment]
Most of this should have been addressed in [Version 1.6.0](https://github.com/SevenTV/SevenTV/releases/tag/1.6.0)
