### ISSUE TITLE
[Bug] 7TV emotes look smaller than BTTV / FFZ emotes

### ISSUE THREAD

**Issue by mopoIo** [SevenTV/SevenTV#217]
**Describe the bug**
7TV emotes look smaller than FFZ/BTTV emotes when using FrankerFaceZ, posted this exact same bug report on their github and they replied with this: [Link](https://github.com/FrankerFaceZ/FrankerFaceZ/issues/1171#issuecomment-1036593378)

**To Reproduce**
1. Enable 7TV add-on.
2. Send a 7TV emote.

**Expected behavior**
All emotes should look the same size.

**Screenshots**
[Screenshot](https://cdn.discordapp.com/attachments/682764268546162704/939448762198269972/unknown.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Other Extensions: [Adblock Plus]

**Comment by AnatoleAM** [comment]
Stendec's response is in fact correct, the image scales on the cdn for `2x` and `3x` are not standard. This will be fixed once emotes are re-processed with the [new Image Processor](https://github.com/SevenTV/ImageProcessor)

**Comment by AnatoleAM** [comment]
At this time recently created emotes will have correct sizes, however this isn't yet applied retroactively to past ones.
