### ISSUE TITLE
[Bug] Incorrect behaviour of moderation slider when user marked by mod as Suspecious is chatting 

### ISSUE THREAD

**Issue by marczeslaw11** [SevenTV/SevenTV#221]
**Describe the bug**
Once user marked as Suspecious types single message, the moderation slider the height of entire chatbox appears. Probably caused by miscalculation of the height of message itself. The big slider disappears once chat scrolls enough to completely deload Suspecious User's messages.

**To Reproduce**
1. Mark user as Suspecious on the channel you moderate
2. Have them post a message
3. You can see the moderation slider bugging on the side - it's displayed on entire height of chatbox, with just a tiny part being clickable

**Expected behavior**
The moderation slider should have the same height as the message, and be possible to drag on the entire height of suspecious user's message

**Screenshots**
![image1](https://user-images.githubusercontent.com/49101610/155005098-bbb54ad9-d460-4fe5-80bb-689613c330d9.png)
![image2](https://user-images.githubusercontent.com/49101610/155005688-73f64244-20ca-4f6a-9513-b879db588724.png)

**Version:**
2.1.4 for Mozilla Firefox

**Comment by Cameron2920** [comment]
The ban slider for suspicious messages isn't displayed correctly because of styling differences between a suspicious message and a normal message. I can probably make a PR to handle this.

**Comment by marczeslaw11** [comment]
Would be appreciated if you did

**Comment by marczeslaw11** [comment]
thanks for help
