### ISSUE TITLE
[Bug] YouTube: Emotes button is missing on Firefox

### ISSUE THREAD

**Issue by 5tayer** [SevenTV/SevenTV#224]
**Describe the bug**
The emotes button on YouTube is missing on Firefox.

**To Reproduce**
1. Go to Youtube on Firefox
2. Go to any livestream with 7tv integration
3. Emotes button is missing

**Expected behavior**
The emotes button should be showing in the bottom right of the chat, next to the send button.

**Screenshots**
![image](https://user-images.githubusercontent.com/74135618/155249931-306464e3-4016-473b-b147-166c17cd250b.png)
Screenshot taken from Ludwig's stream chat (has 7tv integration)

![image](https://user-images.githubusercontent.com/74135618/155262278-fde063a7-7932-438f-a667-fefc4dc39e34.png)
Screenshot taken from a different stream chat (also has 7tv), still no emote button.

**Version:**
7tv 2.1.4 on Firefox Nightly 99.0

**Comment by Cryptizism** [comment]
7TV 2.1.4 works perfectly fine on Firefox Nightly 99.0a1 for me.

My thought is you denied 7TV permission to access YouTube or you have conflicting extensions..

The best bet is to re-install the extension and allow it access to YouTube.com if that doesn't work disable other extensions.

**Comment by 5tayer** [comment]
> My thought is you denied 7TV permission to access YouTube
I appear to have done so. I don't entirely know how.

I reinstalled and it works again. Apologies for the bug report when it was just my mistake. From now on if it breaks like that again I will do a reinstall. Thank you!

**Comment by robmonte** [comment]
Actually I've also noticed this behavior intermittently. Perhaps this isn't what the OP was experiencing, but it seems that occasionally, something causes the extension to not load on a Youtube page. A refresh will always fix it in those instances because it only happens very rarely (<5% rough estimate). Not sure if there's any way to reliably investigate what's happening due to that.
