### ISSUE TITLE
VOD and Clip chat is not supported 

### ISSUE THREAD

**Issue by AnatoleAM** [SevenTV/SevenTV#23]

**Comment by Cryptizism** [comment]
Shouldn't this issue be closed @AnatoleAM? Works fine for me and has worked for awhile IIRC.

**Comment by AnatoleAM** [comment]
> Shouldn't this issue be closed @AnatoleAM? Works fine for me and has worked for awhile IIRC.

It's still not implemented, so no. It would only work if you have FrankerFaceZ installed

**Comment by FourLineCode** [comment]
Is this something thats being worked on? Because I dont use the FFZ extension. The FFZ extension is very bloated and slow, so I would like to only use the 7tv extension if possible..

**Comment by AnatoleAM** [comment]
As far as i'm aware no one is currently on this, as the team is busy with the API v3, the new website and other tasks. Though anyone can submit a pull request. At the latest this feature would come when the web extension get its own major cleanup/overhaul later this year

**Comment by AnatoleAM** [comment]
VOD chat is now supported as #234 was merged. It will be live with version 2.2.0
