### ISSUE TITLE
[Bug] The youtube logo is broken in the "7TV is also on YouTube" message

### ISSUE THREAD

**Issue by elmarceloc** [SevenTV/SevenTV#231]
**Describe the bug**
The fill of the arrow in the youtube play button in the "7TV is also on YouTube" message is not inside the logo when the page is scrolled

**To Reproduce**

1. Go to 7tv.app
2. shrink the page vertically if its nesesary
3. Scroll down

**Expected behavior**
The arrow will need to be inside the youtube logo

**Screenshots**
![image](https://user-images.githubusercontent.com/73359763/157832027-ab88e591-bc72-4b28-b18a-8c6c70d45145.png)

**Version:**
7tv 2.1.4 / Opera 84.0.4316.31 / Windows 10

**Comment by AnatoleAM** [comment]
The current website is deprecated, so while this is a valid bug it won't be fixed as it's going away soon in favor of the [V3-based Vue website](https://github.com/SevenTV/Website)
