### ISSUE TITLE
Trovo platform support

### ISSUE THREAD

**Issue by trueddd** [SevenTV/SevenTV#232]
It would be great to have an opportunity to see lovely emotes on [Trovo](https://trovo.live/) streaming platform.

**Comment by Cryptizism** [comment]
I don't think this will come at all, the platform is extremely small and they would have to put a lot of time and effort into dealing with this which would have basically no reward

**Comment by trueddd** [comment]
I understand that platform is small and very unpopular among streamers community. But Trovo has become primary streaming platform for many CIS content makers which were forced to move on from Twitch cause of their recent statements about payments. So 7TV could be very useful and the only third-party emote service cause BTTV or FFZ don't seem to provide support on Trovo.

**Comment by AnatoleAM** [comment]
It will not be considered yet. If this platforms becomes larger and is able to prove it can self-sustain with a larger user base then maybe.
