### ISSUE TITLE
Support for Alternate Player for Twitch.tv

### ISSUE THREAD

**Issue by vs2961** [SevenTV/SevenTV#233]
Is it possible to check for the Alternate Player for Twitch.tv extension, or do something similar to BetterTTV to integrate it with the chat on Twitch.tv? I would love to use this extension along with my other twitch.tv extensions.

**Comment by AnatoleAM** [comment]
This is something you need to ask the developer of Alternate Player, it runs in a private extension context which other extensions cannot access unless white-listed.

**Comment by CoolCmd** [comment]
The workaround is described in the built-in help of Alternate player.
