### ISSUE TITLE
[Bug] FFZ emotes don't show up in colon autocomplete

### ISSUE THREAD

**Issue by Cryptizism** [SevenTV/SevenTV#237]
**Describe the bug**
When you try to use the colon (:) feature you can't see FFZ emotes, the images are just blank. I'm running 7TV natively and not through FFZ with no other extensions enabled.

**To Reproduce**
1. Go to someone's twitch stream
2. Go into the chat
3. Use the semicolons and type in an emote that's on FFZ
4. Image will fail to appear alongside its name

**Expected behavior**
The emote's image should appear

**Screenshots**

You can see below that there is no src or any image source for the emotes like LULW and OMEGALUL (which are FFZ emotes)

![image](https://user-images.githubusercontent.com/60571306/160217110-492e2822-247d-4683-b6ab-8228ca7f4474.png)

Here is what it looks like on the site

![image](https://user-images.githubusercontent.com/60571306/160217180-1fed4048-0b7a-44ab-bdcd-88473e5b0f19.png)

**Version:**
Latest dev build (as of https://github.com/SevenTV/SevenTV/commit/2d79a432ebd0a5b2ebc1a3d2bf10782460cf2ace) and v2.1.4 on Version 99.0.4844.82 (Official Build) (64-bit)

**Comment by M-TGH** [comment]
I think this might have gotten fixed along in #240 since I can not currently reproduce it on 2.2.0, @Cryptizism can you confirm this to be the case? 👀

**Comment by Cryptizism** [comment]
#240 Has resolved this issue for me, closing.
