### ISSUE TITLE
[Bug] Replying does not work on Twitch website

### ISSUE THREAD

**Issue by cabbagefork** [SevenTV/SevenTV#243]
**Describe the bug**
Twitch chat sends a normal message when trying to reply to somebody

**To Reproduce**
1. Go on any channel with extension enabled
2. Press reply button
3. Type and send message

**Expected behavior (extension off)**
![image](https://user-images.githubusercontent.com/31359599/163724184-95a05c12-8e35-4767-901b-55df3f990263.png)
![image](https://user-images.githubusercontent.com/31359599/163724186-4badb15e-8a6c-4774-bafa-2bfbebff18a8.png)

**Actual behavior (extension on)**
![image](https://user-images.githubusercontent.com/31359599/163724230-827b1b24-849f-4388-b4bb-5ce092f9f79c.png)
![image](https://user-images.githubusercontent.com/31359599/163724233-913d565a-5218-4928-8465-b426052699f6.png)

**Version:**
2.2.0

**Comment by Bucketsmith** [comment]
I've been experiencing the same bug since today.

**Comment by AnatoleAM** [comment]
Located the issue, twitch passes a secondary parameter when replying to a message. That param was being discarded by the IRC middleware added in 2.2

**Comment by AnatoleAM** [comment]
This is now fixed on the development branch and will be live with version 2.2.1
