### ISSUE TITLE
Possible bug in "asBoolean" function

### ISSUE THREAD

**Issue by KeterSCP** [SevenTV/SevenTV#248]
**Describe the bug**
It seems like this function https://github.com/SevenTV/SevenTV/blob/e6079c313654c69e978388e085675e9a6daa6244/src/Global/Util.ts#L124 does not handle correctly configs with `false` value.

**To Reproduce**
1. Open typescript playground [link](https://www.typescriptlang.org/play?ts=4.1.5#code/MYGwhgzhAEDKCmAXRBLAdgcwgNTCArvAIwCwAUAN7nQ3TAD2aEiATvsIvSwBQAOLKAG5hE8aMILwAXNDBoAngEpoFAL7lqtSACF69EPDndFMgEZ6DclZtq0WSfCzTQ08AO7Rd+w2m6IAFigQAHQShIoA3DbQ6mSx5KCQMAjI6Fi4kgBM5FRktgxMrOycPPxCImJh0rIKymoaeVoQXpa+JtDm3la5trb2iI7Orh4tPn6BIVWKoXiEAPIAZsYR0AD0q9AAPAC00BhI0GUAtiiogmILLPRH0G4sYLy88CzQ9KYAVvAc0bHxZAXMV4fL6IDKEAAqbDEAF4XO44EhUJgcLNiH4oZEEoxAcdTkJ4GD4JDCNBYcMEalkYTMujwlEyOQUAtoNw3p8OITifAAPzBHQWMaKOrRAHeYIgegYbgAIjZIM5UMOSTS0CZdH8XwA1tLMXEGmq+AITmcCaiubz+V02sLGjRRQZxZKZbiTQqSbxlZhVczgBrgNrdX8AYggezQaiAGJ4CAwuEeFJI9KoojcBbR+C64OHI1486EqMgGOkuMUxMorKp9O6xnM7gAQjlHMj6YtzQFRiF1ltdGxYolUtlwKbkgLRY9UBVarQ9BDvq1OvpfwNdZd+PzLb5batxht+V7Dv7zpzrubhbE44gk+Z09nfoDi6AA)
2. Click `Run` button

**Expected behavior**
Both `true` and `false` if checks should pass

**Actual behavior**
Only `true` if check passes, if option is false, if body will not execute. You can even see compiler error describing that there is no such cast `Boolean` -> `boolean`

**Version:**
2.2.0

**Additional information**
Noticed this while investigating why moderation timeouts are not shown anymore, but probably I'll report it in another issue.

**Comment by M-TGH** [comment]
That's the difference between `new Boolean(value)` and `Boolean()`.
In these scenarios `new Boolean(value)` results in the Boolean object which is not a proper boolean.
But the `Boolean(value)` function, without the new, returns a primitive type boolean.
Looks like the code is using the correct form;
https://github.com/SevenTV/SevenTV/blob/e6079c313654c69e978388e085675e9a6daa6244/src/Global/Util.ts#L125

**Comment by KeterSCP** [comment]
> That's the difference between `new Boolean(value)` and `Boolean()`. In these scenarios `new Boolean(value)` results in the Boolean object which is not a proper boolean. But the `Boolean(value)` function, without the new, returns a primitive type boolean. Looks like the code is using the correct form;
> 
> https://github.com/SevenTV/SevenTV/blob/e6079c313654c69e978388e085675e9a6daa6244/src/Global/Util.ts#L125

Oh yes, you are right. I missed that there was no `new`. Thanks for pointing out
