### ISSUE TITLE
[Bug] "Allow sending the same message twice" appending U+E0000 when the message is not a duplicate

### ISSUE THREAD

**Issue by MiYanni** [SevenTV/SevenTV#249]
## Description
The "Allow sending the same message twice" is causing problems in chats where the streamer has Nightbot detection of repeated symbols. This causes users to be timed out and unsure of why. I believe there is a bug where it is appending multiple of the U+E0000 character even if the message is not a duplicate.

I was not able to see these characters in the DOM of the webpage after the message was sent. I believe you can copy them out of the chatbox, though. I also got a mod of the channel to send me the characters from using an IRC chat client that has them rendered.

Code for this logic to send U+E000 is here:
https://github.com/SevenTV/SevenTV/blob/e6079c313654c69e978388e085675e9a6daa6244/src/Sites/twitch.tv/Runtime/InputManager.tsx#L120

## Repro
1. Go to https://www.twitch.tv/dolphinchemist
2. Attempt to send a message after waiting 1 minute
3. Observe that Nightbot will time you out

## Expected Result
You will not get timed out for sending your first message

## Screenshots
![image](https://user-images.githubusercontent.com/17788297/163870685-c88f1235-0c52-4886-9c99-3ab581db01a2.png)
There were multiples of these on the first message I sent in the channel.

![image](https://user-images.githubusercontent.com/17788297/163871007-888753fa-da65-4fa2-bc0a-a7fb2abec280.png)
From the mod that helped me diagnose the issue.

## Version
2.2.0

**Comment by AnatoleAM** [comment]
Fixed in 2.2.1 (5f30b092d9df8e9198da1d101579e6d46c952a25)
