### ISSUE TITLE
[Bug] Can't add zero-width emotes to my channel - Insufficient Privilege

### ISSUE THREAD

**Issue by DmitryScaletta** [SevenTV/SevenTV#269]
**Describe the bug**
Can't add zero-width emotes to my channel - Insufficient Privilege

**To Reproduce**
1. Go to any zero-width emote. For example - https://7tv.app/emotes/6116a00a47935f36575c7bbb
2. Click on "Add to channel"
3. See error

**Expected behavior**
Zero-width emote is added to channel.

**Screenshots**
![image](https://user-images.githubusercontent.com/5096735/171696007-a9c13114-c78c-4e71-b466-22d9d093ccf3.png)

**Comment by NanobotZ** [comment]
Are you a 7Tv subscriber?
It is stated on their website that only subscribers can have zero-width emotes.
