### ISSUE TITLE
[Bug] Emotes disappearing when twitch chat scrolls up

### ISSUE THREAD

**Issue by squareSphere29** [SevenTV/SevenTV#286]
**Describe the bug**
Emote changes back to text when the chat scrolls

**To Reproduce**
1. Enter emote name (e.g. KEKW)
2. Send message
3. Emote turns back into text instead of an image

**Expected behavior**
Emote image to remain as an image when chat scrolls up

**Version:**
The version where the bug is occuring (e.g 1.6.0)
2.2.2 Firefox 103.0.2

**Comment by alfredapri** [comment]
Also happens on latest version of Chrome version 104.0.5112.81. And also on version 2.2.2 of 7TV.

**Comment by AnatoleAM** [comment]
Fixed by #287
