### ISSUE TITLE
FFZ "Fix Bad Twitch Global Emotes" gets overridden

### ISSUE THREAD

**Issue by robbai** [SevenTV/SevenTV#31]
The FFZ option:
```
Fix Bad Twitch Global Emotes
Clean up the images for bad Twitch global emotes, removing white borders and solid backgrounds.
```
7TV overrides this option and the emotes are "unfixed", is there any intention for this behaviour to be changed?

**Comment by AnatoleAM** [comment]
I'll have a look into.

**Comment by AnatoleAM** [comment]
With 1.5.4 comes the FrankerFaceZ Add-on Integration #63 which resolves this issue.
