### ISSUE TITLE
Add option to disable the full-size emote viewer on mouse hover

### ISSUE THREAD

**Issue by tunacanman** [SevenTV/SevenTV#33]
It replaces that function of the other extensions. The 7TV version sucks bc it doesn't show the emote channel etc., doesn't look good(too bulky), and it has a visual glitch where for the first frame it renders in a different position before being put in the right position.
Regardless of these issues, it should be an optional feature.

**Comment by hertn** [comment]
has this been fixed? its 2 years later and I cant find any way to disable this feature.
