### ISSUE TITLE
Bit emotes show up as a broken image

### ISSUE THREAD

**Issue by AnatoleAM** [SevenTV/SevenTV#38]

**Comment by zneix** [comment]
Could this be becuase bit emotes use v2 cdn endpoint?

**Comment by AnatoleAM** [comment]
> Could this be becuase bit emotes use v2 cdn endpoint?

It's possible, I cant easily test this currently though since i'd need to be capturing message data and wait for someone to use bits

**Comment by zneix** [comment]
Found the issue - source of the image leads to https://static-cdn.jtvnw.net/emoticons/v2//default/dark/1.0 looks like the ID is missing

![sus](https://cdn.zneix.eu/VDvxHFi.png)

**Comment by AnatoleAM** [comment]
Turns out this issue was primarily because Twitch uses a completely different cdn endpoint for bit emotes, being at "cloudfront.net" instead. In #122 these urls are now inferred from twitch's internals, and the cheer amount is now also rendered by the extension

**Comment by AnatoleAM** [comment]
Fixed by #122 and deployed in 1.6.2
