### ISSUE TITLE
Emotes are misplaced and cause issues

### ISSUE THREAD

**Issue by Rmin-Sadigh** [SevenTV/SevenTV#41]
sometimes the emotes are moved, but still leave the empty space where they originally were supposed to be.

case example
![image](https://user-images.githubusercontent.com/61507499/120602129-f5d13d80-c45f-11eb-80ef-ab37c0c871be.png)

the blank space on the left can be clicked and will open a popup from bttv extension providing the emote info for 'LUL'. this seems to be a conflict between bttv and 7tv extensions.

**Comment by AnatoleAM** [comment]
Fixed in 1.5.2 c0072619a14efb462fa4eae2062e747d0a2cf379
