### ISSUE TITLE
Emote tab autocomplete behaving strangely

### ISSUE THREAD

**Issue by Munzu** [SevenTV/SevenTV#42]
Here's a demonstration:

https://i.imgur.com/q7BHlmL.gif

When I type "OM" and press tab, I expect it to autocomplete "OMEGALUL" and only "OMEGALULiguess" when I press tab one more time.

However, right now, it seems to cycle between those two, even if I start typing from scratch.

Also, trying to type "OMEGALUL" twice messes up the input completely.

**Comment by AnatoleAM** [comment]
This is fixed in 1.5.5. If the issue persists, try disabling BetterTTV
