### ISSUE TITLE
Emote menu duplicates

### ISSUE THREAD

**Issue by KeterSCP** [SevenTV/SevenTV#43]
Steps to reproduce:

- Quickly switch between 2 or more channels on the `Followed channels` panel.

Expected result:

- Emotes menu appears only for the last chosen channel

Actual result:

- Multiple emote menus appear
![image](https://user-images.githubusercontent.com/38229504/120891873-3620ef00-c60b-11eb-85a0-461dd5227740.png)

**Comment by AnatoleAM** [comment]
Fixed in 1.5.4
