### ISSUE TITLE
Massive memory usage on Firefox

### ISSUE THREAD

**Issue by ILogOutOnTheToilet** [SevenTV/SevenTV#59]
### What seems to be the problem?

If I use 7tv for a long time in Firefox 125.0.3 (64-bit) on Windows 10, the memory usage goes up over time until it goes between 99% and 100% in Task Manager and Twitch or Firefox becomes unusable. When I uninstalled 7tv on Firefox, the memory maintained around to 34% with the same Firefox session. I have verified as long as I don't have 7tv installed on Firefox, I don't have the gradually increasing memory usage issue.

### Operating System

Microsoft Windows

### Browser

Mozilla Firefox

### How do we replicate that?

1. Open Firefox 125.0.3 (64-bit).
2. Install 7tv stable build.
4. Open Twitch streams.
5. Open Task Manager and note the memory usage. It should be quite low.
6. Wait for several hours.
7. Open Task Manager and note the memory usage, and it should have jumped significantly higher. If it is hovering between 99% and 100%, it would make Twitch or Firefox unusable.

**Comment by subjectverbagreement** [comment]
Same issue that has led me to disable the extension on Firefox. After seeing memory usage of >10gb multiple times in the FF task manager (and Win 11 task manager), I disabled the 7tv extension. Even without a browser restart, after an hour memory usage remained below 600mb for the same tab (my only open tab). There is obviously something wrong with the extension.

**Comment by matrox471** [comment]
Arch Linux -> Firefox 130.0.1
Doesn't seems to be OS related.
Simply watching a stream with show the ram going up slowly and when the GC kicks in, the ram doesn't go back as low as it was.
I was on stream of Ironmouse and after a few hours (maybe 4 or 5), i max up my 32G of ram.
Refreshing the page obviously reset the memory.
Also, when i invoke the ":" auto complete for the custom emote, i also get a memory spike that keep on growing every time i do the same input. (i assume it wouldn't grow after the first time you type the same thing ?)
I played around in the stack viewer and by doing memory diff, it seems to be coming from 7tv. Seems pretty annoying to debug, sorry i can't help more :(
