### ISSUE TITLE
Empty spaces in chat

### ISSUE THREAD

**Issue by jprochazk** [SevenTV/SevenTV#61]
Same issue as #41, extension is on latest version (1.5.3), it is reproducible in Firefox 88 and Chrome 91.

![image](https://user-images.githubusercontent.com/1665677/122455747-04197080-cfad-11eb-8c98-6059b928963e.png)

**Comment by jprochazk** [comment]
This only seems to happen to Twitch emotes.

First message has a Twitch emote (sodaCOP), second one is BTTV (COPIUM)
![image](https://user-images.githubusercontent.com/1665677/122456684-21027380-cfae-11eb-92bb-1b3408e31de9.png)

**Comment by karl-police** [comment]
sounds similar to https://github.com/SevenTV/SevenTV/issues/53

**Comment by AnatoleAM** [comment]
These "empty spaces" are actually buttons generated by Twitch to open the emote card, normally the extension removes them, but in some situations it doesn't. This will be looked at for fix in version 1.6.0

**Comment by AnatoleAM** [comment]
Fixed in 1.5.4
