### ISSUE TITLE
Emotes alias bug

### ISSUE THREAD

**Issue by Leo777870** [SevenTV/SevenTV#62]
### What seems to be the problem?

Problem is when I try to assign an alias to emote for a channel where I am an editor, it assigns to a random emote, not to desired one. 

### Operating System

Microsoft Windows

### Browser

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, etc.)

### How do we replicate that?

1. Go to profile 
https://7tv.app/users/63fbc75249184efad4d93fac
2. open emote Angry
3. See its renamed, and somehow considered as Shaa (https://7tv.app/emotes/6666fa6c3980527dca7229d7 this one should be Shaa instead)
4. Try to rename it back to Angry
5. error: name conflict. somehow this is considered Angry https://7tv.app/emotes/60b13589ae7a9a2c2446cfef - but it was never ment to be renamed in a first place

**Comment by lennartkloock** [comment]
@Leo777870 Is this fixed now with the new backend?

**Comment by lennartkloock** [comment]
I'm guessing this is no longer an issue
