### ISSUE TITLE
Emotes not cleared upon raid

### ISSUE THREAD

**Issue by Gpax971** [SevenTV/SevenTV#63]
### What seems to be the problem?

When a Channel A raids into Channel B, the emotes from Channel A will still be loaded in chat, while the emotes from Channel B will not. When searching emotes through the emote menu, the emotes are loaded as expected.

After reloading the page, the emotes work as normal.

### Operating System

Microsoft Windows

### Browser

Mozilla Firefox

### How do we replicate that?

1. Watch any channel
2. Get raided into another channel
3. Type any emotes in chat that were valid in the original channel, but not in the new channel

Expected result: text shows up as if emote does not exist
Actual result: emote shows up with all original metadata

**Comment by guptadagger** [comment]
This sometimes happen when just switching channels as well

**Comment by lennartkloock** [comment]
This is a issue related to the [extension](https://github.com/SevenTV/Extension), please create an issue there.
