### ISSUE TITLE
You are colliding with FFZ

### ISSUE THREAD

**Issue by Maj-ew** [SevenTV/SevenTV#64]
You are bugging FrankerFaceZ somehow so pretty often emotes from FFZ don't show on chat or I can't even search them by ":'. Also I can't see channel's ffz emotes in 7tv menu when I press ffz icon there. Maybe there was some update? I don't know I couldn't fix it by reopenning chrome

**Comment by AnatoleAM** [comment]
We're in the process of integrating an FFZ add-on into the extension to mitigate clashing issues. See the pull request #63
