### ISSUE TITLE
Stream video brightness changes when hovering over chat badges on HDR display

### ISSUE THREAD

**Issue by rik-rosseel** [SevenTV/SevenTV#70]
### What seems to be the problem?

The video gets brighter when hovering over badges in twitch chat. 
(Both google chrome and firefox with all other browser addons disabled, the issue is not there when disabling the 7tv addon)

![clideo_editor_c729a2d63a6d4b0cbaea706050ffb9b1](https://github.com/user-attachments/assets/13c05746-25e5-4bb8-b02c-351ac92ebea6)

### Operating System

Microsoft Windows

### Browser

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, etc.)

### How do we replicate that?

1. Open a twitch stream on a HDR display
2. Hover over twitch chat badge icons

**Comment by lennartkloock** [comment]
This is a issue related to the [extension](https://github.com/SevenTV/Extension), please create an issue there.
