### ISSUE TITLE
Site Layout Sidebar no longer works properly

### ISSUE THREAD

**Issue by EnnaelK3219** [SevenTV/SevenTV#72]
### What seems to be the problem?

Site Layout, Sidebar.
"Hide Recommended Channels" now hides the following list.
"Hide Viewers Also Watch" now hides the recommended channels.

Version 3.1.1, Google Chrome extension.

### Operating System

Microsoft Windows

### Browser

Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, etc.)

### How do we replicate that?

1.  go on twitch.tv in any chatroom, live or not doesn't matter
2.  go into 7tv options
3.  click on Site Layout, then Sidebar
4. Toggle the only two options in this section to reproduce current reported results

**Comment by FizzyColaBottles** [comment]
I think happened when Twitch added the Open Stories section on that sidebar - can as part of the fix also have the ability to hide that section, like we have for the other sections

**Comment by lennartkloock** [comment]
This is a issue related to the [extension](https://github.com/SevenTV/Extension), please create an issue there.
