### ISSUE TITLE
Userscript

### ISSUE THREAD

**Issue by denimchewer56** [SevenTV/SevenTV#76]
Having 7TV as a userscript would be fantastic, enabling people using other browsers, particularly Safari users to use 7TV.

**Comment by Melonify** [comment]
I don't believe a userscript would be possible at the moment, as the extension relies heavily on WebExtension specific features.

An alternative however would be to use the FFZ userscript and enable the 7TV emotes addon.

**Comment by AnatoleAM** [comment]
At this time this is not possible, but may be considered at a later date. Third party implementations are also welcome.
