### ISSUE TITLE
TabComplete doesn't get reset in certain situations

### ISSUE THREAD

**Issue by sensor** [SevenTV/SevenTV#84]
Begin typing "omega" then press tab, select all of the text and either press the "Delete" key on your keyboard or right click and use the "Delete" from the context menu in a browser. Then try to tabcomplete anything else and all it will complete is the previous OMEGALUL or what ever else it completed from this example.

I think it's because in TabCompleteDetection.tsx on line 32 there's only a check for Space / BackSpace and Enter. 

Easiest fix would be to add a check for "Delete" on that line however I think that part of the code should be refactored so you don't need to add all these different keycodes & checks.

**Comment by Melonify** [comment]
This issue has been resolved in #98
